use crate::models::{PodcastTranscript, PodcastChapter, PodcastSoundbite, PodcastPerson, PodcastValue, PodcastValueRecipient};

pub struct ParserState {
    // Feed-level metadata
    pub current_element: String,
    pub feed_type: i32,

    // Channel-level flags
    pub in_channel: bool,
    pub in_channel_atom_author: bool,
    pub in_channel_image: bool,
    pub in_channel_itunes_owner: bool,
    pub in_channel_podcast_funding: bool,
    pub in_channel_podcast_locked: bool,
    pub in_channel_podcast_value: bool,

    // Channel-level fields
    pub channel_atom_author_email: String,
    pub channel_atom_author_name: String,
    pub channel_description: String,
    pub channel_explicit: i32,
    pub channel_generator: String,
    pub channel_image: String,
    pub channel_itunes_author: String,
    pub channel_itunes_categories: Vec<String>,
    pub channel_itunes_image: String,
    pub channel_itunes_new_feed_url: String,
    pub channel_itunes_owner_email: String,
    pub channel_itunes_owner_name: String,
    pub channel_itunes_summary: String,
    pub channel_itunes_type: String,
    pub channel_language: String,
    pub channel_last_build_date: i64,
    pub channel_link: String,
    pub channel_podcast_funding_text: String,
    pub channel_podcast_funding_url: String,
    pub channel_podcast_guid: String,
    pub channel_podcast_locked: i32,
    pub channel_podcast_owner: String,
    pub channel_podcast_values: Vec<PodcastValue>,
    pub channel_pub_date: i64,
    pub channel_pubsub_hub_url: String,
    pub channel_pubsub_self_url: String,
    pub channel_title: String,
    pub channel_value_model_method: String,
    pub channel_value_model_suggested: String,
    pub channel_value_model_type: String,
    pub channel_value_recipients: Vec<PodcastValueRecipient>,

    // Item-level flags
    pub in_item: bool,
    pub in_item_image: bool,
    pub in_itunes_author: bool,
    pub in_podcast_alternate_enclosure: bool,
    pub in_podcast_funding: bool,
    pub in_podcast_person: bool,
    pub in_podcast_soundbite: bool,
    pub in_podcast_value: bool,
    pub item_has_valid_enclosure: bool,

    // Item-level fields
    pub content: String,
    pub content_encoded: String,
    pub current_person_group: String,
    pub current_person_href: String,
    pub current_person_img: String,
    pub current_person_name: String,
    pub current_person_role: String,
    pub current_soundbite_duration: String,
    pub current_soundbite_start: String,
    pub current_soundbite_title: String,
    pub description: String,
    pub enclosure_length: String,
    pub enclosure_type: String,
    pub enclosure_url: String,
    pub guid: String,
    pub item_image: String,
    pub item_itunes_author: String,
    pub itunes_duration: i32,
    pub itunes_episode: String,
    pub itunes_episode_type: String,
    pub itunes_explicit: i32,
    pub itunes_image: String,
    pub itunes_season: String,
    pub itunes_summary: String,
    pub itunes_title: String,
    pub link: String,
    pub podcast_chapters: Vec<PodcastChapter>,
    pub podcast_funding_text: String,
    pub podcast_funding_url: String,
    pub podcast_persons: Vec<PodcastPerson>,
    pub podcast_soundbites: Vec<PodcastSoundbite>,
    pub podcast_transcripts: Vec<PodcastTranscript>,
    pub podcast_values: Vec<PodcastValue>,
    pub pub_date: i64,
    pub title: String,
    pub value_model_method: String,
    pub value_model_suggested: String,
    pub value_model_type: String,
    pub value_recipients: Vec<PodcastValueRecipient>,

    // Item metrics
    pub item_count: i32,
    pub item_pubdates: Vec<i64>,
}

impl Default for ParserState {
    fn default() -> Self {
        Self {
            // Feed-level metadata
            current_element: String::new(),
            feed_type: 0,

            // Channel-level flags
            in_channel: false,
            in_channel_atom_author: false,
            in_channel_image: false,
            in_channel_itunes_owner: false,
            in_channel_podcast_funding: false,
            in_channel_podcast_locked: false,
            in_channel_podcast_value: false,

            // Channel-level fields
            channel_atom_author_email: String::new(),
            channel_atom_author_name: String::new(),
            channel_description: String::new(),
            channel_explicit: 0,
            channel_generator: String::new(),
            channel_image: String::new(),
            channel_itunes_author: String::new(),
            channel_itunes_categories: Vec::new(),
            channel_itunes_image: String::new(),
            channel_itunes_new_feed_url: String::new(),
            channel_itunes_owner_email: String::new(),
            channel_itunes_owner_name: String::new(),
            channel_itunes_summary: String::new(),
            channel_itunes_type: String::new(),
            channel_language: String::new(),
            channel_last_build_date: 0,
            channel_link: String::new(),
            channel_podcast_funding_text: String::new(),
            channel_podcast_funding_url: String::new(),
            channel_podcast_guid: String::new(),
            channel_podcast_locked: 0,
            channel_podcast_owner: String::new(),
            channel_podcast_values: Vec::new(),
            channel_pub_date: 0,
            channel_pubsub_hub_url: String::new(),
            channel_pubsub_self_url: String::new(),
            channel_title: String::new(),
            channel_value_model_method: String::new(),
            channel_value_model_suggested: String::new(),
            channel_value_model_type: String::new(),
            channel_value_recipients: Vec::new(),

            // Item-level flags
            in_item: false,
            in_item_image: false,
            in_itunes_author: false,
            in_podcast_alternate_enclosure: false,
            in_podcast_funding: false,
            in_podcast_person: false,
            in_podcast_soundbite: false,
            in_podcast_value: false,
            item_has_valid_enclosure: false,

            // Item-level fields
            content: String::new(),
            content_encoded: String::new(),
            current_person_group: String::new(),
            current_person_href: String::new(),
            current_person_img: String::new(),
            current_person_name: String::new(),
            current_person_role: String::new(),
            current_soundbite_duration: String::new(),
            current_soundbite_start: String::new(),
            current_soundbite_title: String::new(),
            description: String::new(),
            enclosure_length: String::new(),
            enclosure_type: String::new(),
            enclosure_url: String::new(),
            guid: String::new(),
            item_image: String::new(),
            item_itunes_author: String::new(),
            itunes_duration: 0,
            itunes_episode: String::new(),
            itunes_episode_type: String::new(),
            itunes_explicit: 0,
            itunes_image: String::new(),
            itunes_season: String::new(),
            itunes_summary: String::new(),
            itunes_title: String::new(),
            link: String::new(),
            podcast_chapters: Vec::new(),
            podcast_funding_text: String::new(),
            podcast_funding_url: String::new(),
            podcast_persons: Vec::new(),
            podcast_soundbites: Vec::new(),
            podcast_transcripts: Vec::new(),
            podcast_values: Vec::new(),
            pub_date: 0,
            title: String::new(),
            value_model_method: String::new(),
            value_model_suggested: String::new(),
            value_model_type: String::new(),
            value_recipients: Vec::new(),

            // Item metrics
            item_count: 0,
            item_pubdates: Vec::new(),
        }
    }
}
